### ISSUE TITLE
CSLANG CLI takes too long to start

### ISSUE THREAD

**Issue by avigail-oron** [CloudSlang/CloudSlang.github.io#100]
on my laptop it takes 13 seconds to start (Windows 7)
if required, i have saved the execution.log file and can supply it.

**Comment by meirwah** [comment]
supply it

**Comment by avigail-oron** [comment]
Attached.
It contains 2 launches of the CLI. (I wanted to make sure it’s doesn’t happen in the first time only)

**Comment by orius123** [comment]
I think we should start by deciding what is the requirement.
I think more than 3 seconds fills slugish..

**Comment by meirwah** [comment]
agree, 3 sec should be our limit

**Comment by meirwah** [comment]
we have issue on this in CloudSlang repo:
https://github.com/CloudSlang/cloud-slang/issues/294

closing this...
