### ISSUE TITLE
projects unupdated in docs - missing the content project...

### ISSUE THREAD

**Issue by meirwah** [CloudSlang/CloudSlang.github.io#103]
![image](https://cloud.githubusercontent.com/assets/6059211/7272886/0d9429fa-e8f7-11e4-84ba-4262ff193b09.png)

**Comment by SamMarkowitz** [comment]
This diagram was meant only for the dependencies. Is the content now dependent on something?

If yes, what is it dependent on?
If not,  should I:
- make it more clear that this is a dependency diagram
- add the non-dependent repos floating by themselves

In any case: the cloud-slang-sdk name is wrong and I will fix it.

**Comment by meirwah** [comment]
ok, so leave content out..
