### ISSUE TITLE
Remove link to Google Plus from website

### ISSUE THREAD

**Issue by gfachler** [CloudSlang/CloudSlang.github.io#111]
I agreed with @meirwah Meir that we should remove link to Google Plus from community section of website as we want to focus investment on Twitter (Twitter also brings much more hits to the site)

**Comment by meshipeer** [comment]
what about people that dont have twitter?

**Comment by meirwah** [comment]
![image](https://cloud.githubusercontent.com/assets/6059211/7451688/2cf277d4-f25c-11e4-8d51-7561ef7c5a6b.png)

**Comment by meshipeer** [comment]
ok....

**Comment by orius123** [comment]
done
