### ISSUE TITLE
The run flow using CSlang example on the website is not visible enough and confusing

### ISSUE THREAD

**Issue by nirgur** [CloudSlang/CloudSlang.github.io#127]
1.	the user should click on the bar to see it, some users can miss it, this should be more visible
2.	After clicking the bar it’s not clear what the user should type and what is the command output, it’s seems like the user is typing the output as well

**Comment by orius123** [comment]
@gal1419 is it fixed in the new site?

**Comment by gal1419** [comment]
we have removed this example from the new website.
The getting started section is much clearer now. 

@nirgur see the getting started in the new website. 
http://cloudslang-gal.herokuapp.com/#/
