### ISSUE TITLE
The community link should open the community page and not scroll to the developers pics

### ISSUE THREAD

**Issue by nirgur** [CloudSlang/CloudSlang.github.io#129]
I've been told that there is a footer at the end of the page but i'ts missing

**Comment by orius123** [comment]
missing footer in @nirgur computer.

**Comment by oritstone** [comment]
@nirgur see the getting started in the new website. 
http://cloudslang-gal.herokuapp.com/#/getstarted

**Comment by gal1419** [comment]
fixed in the new website
