### ISSUE TITLE
Need to move docs to  readthedocs platform 

### ISSUE THREAD

**Issue by meirwah** [CloudSlang/CloudSlang.github.io#131]
We MUST support versions in our documnation, and we should do that with : https://readthedocs.org/

**Comment by orius123** [comment]
:+1:

**Comment by meirwah** [comment]
is there anything left to do here?
cam we close it @SamMarkowitz ?
do we support versions now?

**Comment by SamMarkowitz** [comment]
Yes, we support versions. I think I need to take one last check that
everything is pointing to the right place.

There are still several issues that affect us that RTD is working on
fixing, such as switching between versions and search don't work.

**Comment by orius123** [comment]
Did you tag the docs for 0.8?

**Comment by SamMarkowitz** [comment]
Nope. Just made a v0.8 branch.
