### ISSUE TITLE
New website - get started section

### ISSUE THREAD

**Issue by Bonczidai** [CloudSlang/CloudSlang.github.io#136]
section: http://www.cloudslang.io/#/getstarted#top : 

- Execute CLI: `Go to cslang/bin/cslang ` should be `Go to cslang/bin/ `
- Run a workflow: incorrect path (for 0.8.0) - should be `run --f ../content/io/cloudslang/base/print/print_text.sl --i text=Hi`

**Comment by meirwah** [comment]
@SamMarkowitz

**Comment by meirwah** [comment]
fixed by #138
