### ISSUE TITLE
getstarted section

### ISSUE THREAD

**Issue by meirwah** [CloudSlang/CloudSlang.github.io#139]
unzip cmd is mentioned twice:

![image](https://cloud.githubusercontent.com/assets/6059211/9386046/65b08ce0-4762-11e5-9d68-1751872cd52e.png)

we can remove the one is step 2.

**Comment by SamMarkowitz** [comment]
It still bothers me that it's not clear that step 2 is not for Docker.

I suggest getting rid of step 2 and turning step 1 into `Download & Run`

**Comment by meirwah** [comment]
:+1:
