### ISSUE TITLE
website page is blank...

### ISSUE THREAD

**Issue by meirwah** [CloudSlang/CloudSlang.github.io#145]
![image](https://cloud.githubusercontent.com/assets/6059211/9640592/0a82a408-51bb-11e5-94bb-b041da704106.png)

using chrome version 44.0.2403.157

**Comment by gal1419** [comment]
Whay seems to be the problem?
Is it not loading at all?

I can see it fine from mobile

**Comment by meirwah** [comment]
yes..

I can also see it from my mobile.. weird..

**Comment by gal1419** [comment]
I can see it also from the desktop .
Can you recreate it? It could be temporary connection problem

**Comment by orius123** [comment]
Any errors in console?

**Comment by meirwah** [comment]
in the image...

**Comment by oritstone** [comment]
Not reproducible
