### ISSUE TITLE
Download CLI from website for linux users?

### ISSUE THREAD

**Issue by meirwah** [CloudSlang/CloudSlang.github.io#147]
I think we have an issue in our download page...
It's unfriendly for the Linux user, since he cannot see the download link , so he cannot copy paste it...
I think we should give instructions suitable for Linux users (like to last version..)

**Comment by meirwah** [comment]
@SamMarkowitz @orius123 @gfachler @gal1419

**Comment by orius123** [comment]
Y can't he see the link?
If he has a browser he can and if he doesn't where would he read the instructions?

**Comment by meirwah** [comment]
Yes but the download will make him download the zip file (not the Tar), where can he see the links for the Tar file?

**Comment by meirwah** [comment]
And he can be like me , using Win on my machine to watch the web-site, but installing it on a remote linux machine...

**Comment by orius123** [comment]
Ok. We can just add a wget example with the .tar

**Comment by meirwah** [comment]
Yep, that makes sense!
@SamMarkowitz @gal1419 @gfachler can you work on this?

**Comment by SamMarkowitz** [comment]
I'm trying to figure out how to do this with out making the download page look like a mess, be too confusing and a pain to maintain. Maybe we'll take a few minutes to figure this out together @oritstone @gfachler?

**Comment by gal1419** [comment]
@SamMarkowitz let's sit on it next week. I may be able to help..

**Comment by oritstone** [comment]
@meirwah @orius123 
We decided to go with a split button for downloading from windows or from linux:
![image](https://cloud.githubusercontent.com/assets/7547370/11021373/0a26c07c-8648-11e5-9b1e-279e4bd58f47.png)
Do you think it is enough or is it important to have the linux command written somewhere as well?
I think the page is much more elegant without it...

**Comment by meirwah** [comment]
Not enough... you need the cmd for the Linux...

**Comment by orius123** [comment]
Really nice graphics! 
But I also think that linux users will be comfortable with a link.
Did you look in other sites?
