### ISSUE TITLE
Add images for OpenShift on workwith folder

### ISSUE THREAD

**Issue by mbettan** [CloudSlang/CloudSlang.github.io#148]
Hello, It would be great to add images for new content recently added like OpenShift, Stackato, AWS, Google Cloud Platform, Chef, HP Public Cloud in workwith folder

Thanks

**Comment by meirwah** [comment]
@mbettan you mean our website?

![image](https://cloud.githubusercontent.com/assets/6059211/10267180/5d667d12-6a92-11e5-8e85-3409e78de70a.png)

**Comment by mbettan** [comment]
Yes, exactly

**Comment by oritstone** [comment]
@gal1419 can you handle this?

**Comment by gal1419** [comment]
I'm on it

**Comment by SamMarkowitz** [comment]
I have a PR for this already. I think it's assigned to you for review.

**Comment by gal1419** [comment]
Yep, just so that

**Comment by gal1419** [comment]
looks good

**Comment by meirwah** [comment]
@oritstone  don't froget to contact OpenShift team.. https://commons.openshift.org/
