### ISSUE TITLE
CloudSlang website only focused on DevOps technology - Proposal review

### ISSUE THREAD

**Issue by mbettan** [CloudSlang/CloudSlang.github.io#153]
Hello,

My 2 cents about the current home page website. It is based on customer feedbacks. 

My opinion is that we should not focus CloudSlang website (and mostly homepage) on DevOps use cases and technologies only. It's very restrictive and It sounds for new people like CloudSlang usage is only for around Docker, Jenkins, CoreOS to help new DevOps team to automate.

Unfortunately, it sounds as another tool for Docker ecosystem only, which is not the case. It would be great to have it more attractive like best-in-class orchestration technology for YAML textual design.

We should announce a process-based orchestrator engine for runbook automation uses cases (Incident Remediation, Fullfillment, User management, disaster recovery, ...). Same story than HP OO around the use cases.

We should also show the textual design through YAML DSL based value (standard de facto), Python and JAVA native capabilities with enterprise grade engine.

What do you think about this proposal ?

Thanks for comments and review.

```
Automate your DevOps use cases using ready-made workflows
```

```
What is CloudSlang?

CloudSlang is an open source tool for orchestrating popular DevOps technologies, such as Docker and CoreOS in an agentless manner. Use ready-made workflows or define your own custom ones. CloudSlang workflows are reusable, shareable and easy to understand.
```

**Comment by oritstone** [comment]
Thanks @mbettan for your suggestion
We need to think about it - whether we want to change our focus or not

**Comment by mbettan** [comment]
Any update on the topic? 1.0 milestone?
More and more contents are less DevOps use cases oriented.

By the way, CloudSlang 3 minutes is not aligned with DevOps focus (https://youtu.be/zMKagFLnQzM?t=4), if you watch the video, it's much more RBA oriented - I think it's a better positionning.

Moreover, I think we also need to differentiate more with Config Mgmt (Puppet, Chef, Ansible, SaltStack) to explain the positionning.
