### ISSUE TITLE
Add name of CloudSlang executable to Get Started instructions

### ISSUE THREAD

**Issue by SamMarkowitz** [CloudSlang/CloudSlang.github.io#163]
From Tomer's feedback.

**Comment by gal1419** [comment]
Hi 

Could you please send me the feedback? 
I'm not sure what suppose to do..

**Comment by oritstone** [comment]
We should add specifically the name of the executable (cslang) to the section:
![image](https://cloud.githubusercontent.com/assets/7547370/11496338/cfb9e0c0-9819-11e5-8a78-f747030c9c24.png)
