### ISSUE TITLE
CloudSlang 3 minutes review

### ISSUE THREAD

**Issue by mbettan** [CloudSlang/CloudSlang.github.io#173]
Hello Sam, all,

It would be great if we can update the CloudSlang 3 minutes video to improve it adding new contents and ideas but also new logos. 
https://youtu.be/zMKagFLnQzM?t=4

@SamMarkowitz - You can contact me we can work together to update it?

I think this video is really important in the front page, as it's the first thing a new visitor will watch (621 views today).

**Comment by SamMarkowitz** [comment]
Indeed, I think we'll need to evaluate which of our current videos need updating. Especially if we're changing the focus of the site.

We'll keep you posted on developments.

**Comment by SamMarkowitz** [comment]
Ok @mbettan. Let's discuss your ideas.

**Comment by mbettan** [comment]
Take a look to Ansible video homepage  http://www.ansible.com/

My 2 cents below 

Keep 3 minutes, perfect timing, but speaker more quickly

1) Music like this one
2) CloudSlang as an opensouce RunBookAutomation tool, we need to understand what is an orchestrator and make a difference between config mgmt (like puppet ansible chef) or container orchestrator/scheduler (mesos kubernetes), probably we defuse it at the beginning
3) Show a Swiss knife for presenting use cases range from xxx to xxx (like you did in your slide with examples)
4) Explain today pains and how CloudSlang solve it
5) Show more logos and contents, not only Docker, to attract new people to browse the content
6) Show the Architecture diagram you recently made with Tomer
7) Introduce OO Enterprise, dual authoring experience graphical and textual?

I think new people don't understand why it's a proven technology, so we probably explain more why

I can share you my current slidedeck on Lync, can help to give you ideas.

**Comment by SamMarkowitz** [comment]
Adding @gfachler and @meshipeer.

**Comment by andreivasiletruta** [comment]
closing for now. new story will be created and video around it too.
