### ISSUE TITLE
Broken link on main cloudslang page

### ISSUE THREAD

**Issue by lrevnic** [CloudSlang/CloudSlang.github.io#181]
Due to the cloud folder reorg in CS the main page contains a broken link:
https://github.com/CloudSlang/cloud-slang-content/blob/master/content/io/cloudslang/openstack/openstack_health_check.sl

**Comment by gal1419** [comment]
Hi, 
what is the new link?

**Comment by SamMarkowitz** [comment]
https://github.com/CloudSlang/cloud-slang-content/blob/master/content/io/cloudslang/cloud/openstack/openstack_health_check.sl
