### ISSUE TITLE
issue while running sl using java spring boot

### ISSUE THREAD

**Issue by ranjith1976** [CloudSlang/CloudSlang.github.io#192]
Hi, I created a sl workflow using http client. And using CLI i was able to execute it successfully. But when i tried to execute the same using spring boot web app, it says System Failure.
But when i tried to execute a simple sl which prints a text using python, it worked fine using spring boot. And it is failing while i used a java-client.
The jar file is in my repository. 

And along with, i did one more experiment by adding the http-client jar as dependency, but maven compilation failing with a warning called unused declared dependencies found: on http-client jar.

Is there anything i need to make sl file with httpclient run from spring boot? Any help would be appreciated. Thanks much.

Another point: I created my own Action class, and it worked in CLI but again didnt get called via java_action. It seems while running using cloudslang webapp, only python_action is getting called not java_action

**Comment by Bonczidai** [comment]
Hi @ranjith1976 

- can you please specify version of CloudSlang are you using?
- is the webapp implemented by you, is it on GitHub?
- it would also be helpful to see the error messages from the logs

I believe the error is related to the versioning capabilities for Java actions. It uses Maven mechanism to resolve dependencies. If your java action uses gav like `gav: group:artifact:version` ~
```yaml

  java_action:
    gav: 'io.cloudslang.content:cs-http-client:0.1.68'
    class_name: io.cloudslang.content.httpclient.HttpClientAction
    method_name: execute
```

you will need to configure the maven related part. You can take the CLI as an example. Under /configuration/cslang.properties` you can find the maven related properties:

```properties
maven.home=${app.home}/maven/apache-maven-3.3.9
maven.multiModuleProjectDirectory=${app.home}/maven/apache-maven-3.3.9
maven.settings.xml.path=${app.home}/maven/conf/settings.xml
maven.m2.conf.path=${app.home}/maven/conf/m2.conf
cloudslang.maven.repo.local=${app.home}/maven/repo
cloudslang.maven.repo.remote.url=http://repo1.maven.org/maven2
cloudslang.maven.plugins.remote.url=http://repo1.maven.org/maven2
```

Your java action (along with its dependencies) need to be placed either in the remote maven repo or the local one (`${app.home}/maven/repo`). If the webapp is implemented by you - you will need to programatically set these system properties (example [here](https://github.com/CloudSlang/cloud-slang/blob/master/cloudslang-tests/src/test/java/io/cloudslang/lang/systemtests/SystemsTestsParent.java#L63))

If you provide more details, I will be happy to assist

**Comment by Bonczidai** [comment]
adding @CimpeanRadu

**Comment by ranjith1976** [comment]
Thank you for quick response. I debugged the code and noticed that
java_actions are failing while executing and it was throwing a Null
Pointer. And it is happening while trying to access MAVEN_M2_CONF_PATH in
the line below of
        System.setProperty(MavenConfig.MAVEN_CLASSWORLDS_CONF_PROPERTY,
System.getProperty(MavenConfig.MAVEN_M2_CONF_PATH));
in DependencyServiceImpl

Is there anything i need to do for this? I tried to add maven.m2.conf.path
in system,properties as well as as env variable

On Thu, Feb 2, 2017 at 12:21 PM, Bonczidai Levente <notifications@github.com

**Comment by Bonczidai** [comment]
you should set all the properties enumerated in my previous comment similar to [this](https://github.com/CloudSlang/cloud-slang/blob/master/cloudslang-tests/src/test/java/io/cloudslang/lang/systemtests/SystemsTestsParent.java#L97) and of course populate the paths accordingly (e.g. put the m2.conf file in the path specified as system property - in a similar way the CLI does)

Is the system property value accessible when you get to the problematic line?

**Comment by ranjith1976** [comment]
Thank you Bonczidai, it was the issue with configuration as you mentioned. I changed the cslang to appropriate repository and it worked .
