### ISSUE TITLE
Issue while defining number value in sl file

### ISSUE THREAD

**Issue by ranjith1976** [CloudSlang/CloudSlang.github.io#197]
I was trying the below sl through the java program it is failing saying that number is not allowed
operation:
-----------SL File----------
  name: print
  inputs:
    - text
    - value: "10"
  python_action:
    script: print value

  results:
    - WORKING: ${true}
    - FAILING
----------------SL File end --------------

Error is lke: Error occurred while executing flow [sample] java.lang.RuntimeException: For operation 'print' syntax is illegal. Input: 'value' should have a String value, but got value '10' of type Integer.

But this working from CLI console. What could be the reason? and what should i do to use run it via java program.

**Comment by andreivasiletruta** [comment]
@ranjith1976 did you try to str the value?
Where exactly are you running the code?

**Comment by andreivasiletruta** [comment]
This issue was moved to CloudSlang/cloud-slang#982
