### ISSUE TITLE
add terms of use to website

### ISSUE THREAD

**Issue by gfachler** [CloudSlang/CloudSlang.github.io#38]
We need both terms of use and privacy policy for HP. @dorsha please add the following links at the bottom of the page pointing to the following URLs:
Terms of use: http://www8.hp.com/us/en/privacy/terms-of-use.html
Privacy Policy: http://www8.hp.com/us/en/privacy/privacy.html 
You can remove the sentence "This website incorporates HP's Privacy Policy" and just replace it with these 2 links

**Comment by orius123** [comment]
terms of use of what? the CLI?
