### ISSUE TITLE
Add community section to website

### ISSUE THREAD

**Issue by gfachler** [CloudSlang/CloudSlang.github.io#39]
I recommend creating a **Community** section on our website to consolidate all community activities. This section would include links to the following:
* Blogs
* social media (Twitter etc.) - This is instead of being at the bottom of the page
* google mailing list (https://groups.google.com/d/forum/score)
* roadmap (_future_)
* how to contribute (_future_). This would be web version based on contributor.md 

The link to this  section would be at the top of the page and would replace the current **blog** link.
We could also call this section **Get Involved**
WDYT?

**Comment by meirwah** [comment]
can you give an example of such page on another OSS website? so we get the idea?

**Comment by gfachler** [comment]
Here are 3 examples with a community/get involved page linked from the main menu
* http://appium.io/get-involved.html?lang=en
* http://hibernate.org/community/ 
* http://www.mongodb.org/get-involved
* http://manageiq.org/community/
I don't picture it exactly the same as these. 
Rather I see it as a section of the site with links (and not a separate page) similar to the way the other parts of our site are laid out. I would also keep it less wordy :)

Note that many sites have all these as part of a dropdown (e.g. https://angularjs.org/ has a dropdown called "discuss". http://jenkins-ci.org/ has a dropdown called connect) but we are not using drop-downs at all

**Comment by meirwah** [comment]
Ok.. makes sense :+1:

**Comment by gfachler** [comment]
@arjuan what do you think?

**Comment by arjuan** [comment]
:thumbsup:

**Comment by orius123** [comment]
@gfachler 
is there anything in particular that you think we must add to the site before publishing?
you can see http://cloudslang.io for the current status

**Comment by gfachler** [comment]
@orius123 
The google mailing list changed to https://groups.google.com/forum/#!forum/cloudslang

**Comment by orius123** [comment]
@gfachler  any chance for a mock?
