### ISSUE TITLE
Update CLI version to get /latest

### ISSUE THREAD

**Issue by orius123** [CloudSlang/CloudSlang.github.io#45]
need to get the zip of the latest release from github

**Comment by orius123** [comment]
dependes on #46

**Comment by meirwah** [comment]
Do we really want to update this to latest? what if latest is unstable?
i think we should stick for now to manually change version at website...

**Comment by orius123** [comment]
Agree. But we still need to update now :wink:

**Comment by meirwah** [comment]
of course...

**Comment by SamMarkowitz** [comment]
Let me know when there is a particular one we should be pointing to and I'll update it everywhere.

**Comment by meirwah** [comment]
https://github.com/CloudSlang/cloud-slang/releases/tag/cloudslang-0.7.4

**Comment by meirwah** [comment]
of course point to the CLI zip...

**Comment by orius123** [comment]
Tested?

**Comment by meirwah** [comment]
i think @Bonczidai run the cluster flows with it... right @Bonczidai ?
do you think we need more testing?

**Comment by Bonczidai** [comment]
right, the cluster flows work with this release

**Comment by orius123** [comment]
I would check runtime error handling of the cli because of shehab fix

**Comment by meirwah** [comment]
which type? thrown from action? flow? give please a use-case..

**Comment by orius123** [comment]
Input output and result bindings + action exception

**Comment by meirwah** [comment]
tested python action exception , seems ok...
what in Input output and result bindings?

**Comment by orius123** [comment]
None.id() should work..

**Comment by meirwah** [comment]
What is None.id()?

**Comment by meirwah** [comment]
@orius123 ?

**Comment by orius123** [comment]
Example for a wrong expression, 'hdhdhddhdyuehjf' will also work.

**Comment by meirwah** [comment]
tested..

**Comment by meirwah** [comment]
@SamMarkowitz  feel free to update website..

**Comment by SamMarkowitz** [comment]
PR #62. First come, first served.

**Comment by orius123** [comment]
updated to 0.7.4

**Comment by SamMarkowitz** [comment]
@meirwah How about the readme files in cloud-slang and cloud-slang-content. Should they point to the latest or the stable version.

**Comment by meirwah** [comment]
stable version

**Comment by meirwah** [comment]
and maybe add something like .. if you want the latest snapshot look at...
