### ISSUE TITLE
new web page for download to track analytics

### ISSUE THREAD

**Issue by gfachler** [CloudSlang/CloudSlang.github.io#53]
I discussed with Dorsha how we can capture download statistics from the website. Right now the download button points directly to GitHub. He proposed that we create a new page on our site for the download. When a user clicks download, it will go this new page and then user will automatically be redirected to Github. it should not affect user but it will enable us to have google analytics data for downloads.

**Comment by orius123** [comment]
done.
@dorsha we need to check that we can see it in google analytics

**Comment by dorsha** [comment]
We can:

[image: Inline image 1]

**Comment by dorsha** [comment]
We can:
![image](https://cloud.githubusercontent.com/assets/5429033/6958123/c1305a80-d90f-11e4-85d6-10bd0643cba0.png)
