### ISSUE TITLE
Revert Images

### ISSUE THREAD

**Issue by meirwah** [CloudSlang/CloudSlang.github.io#63]
It looks really bad...

**Comment by orius123** [comment]
http://www.ipetitions.com/petition/change-images-to-gh-avatars
:smile:

**Comment by orius123** [comment]
@Asisayag WDYT?

**Comment by meirwah** [comment]
@dorsha can you add pics example to here???

**Comment by dorsha** [comment]
![1](https://cloud.githubusercontent.com/assets/5429033/7219463/e1a009da-e6a9-11e4-9311-da05864a3a7e.jpg)
![2](https://cloud.githubusercontent.com/assets/5429033/7219464/e1bf45ca-e6a9-11e4-9e63-7ea9033afc52.jpg)

**Comment by meirwah** [comment]
@orius123 @meshipeer @oritstone  WDYP ???

**Comment by orius123** [comment]
I thought we decided to remove the images..

**Comment by dorsha** [comment]
Take a look at the attached GitHub cards.. these are not images...
http://cloudslang-github-cards.herokuapp.com/#/

**Comment by orius123** [comment]
it's really nice. but it is still images of people and it requires maintenance etc...
plus, regarding the github cards, I think that it shows that we are all noobs...

**Comment by dorsha** [comment]
It takes the images and data from the github profiles so it is not requires maintenance.

**Comment by meshipeer** [comment]
i like it. Asi also approved...
i agree we need to improve our numbers

**Comment by orius123** [comment]
Ok.. any other themes?

**Comment by meirwah** [comment]
no other themes...
so merge it?

**Comment by orius123** [comment]
@dorsha how does it affect performance? It's. Few more http calls.

**Comment by meirwah** [comment]
we need to take a decision here

**Comment by meirwah** [comment]
Another option is to replace this with logos of our content intergrations(consul,docker,marathon, jenkins...)   , and add the caption : "we play along with ..."

**Comment by meshipeer** [comment]
i understand Eliya & Orit don't want this as is.
we can consider create another style \ layout of the cards - but i don't think its for now!
we will remove the images for now - just need Hadar to decide what to place instead.....

**Comment by meirwah** [comment]
but eliya says it is an issue to remove the images...

**Comment by meirwah** [comment]
Can we please reach a decision here????

**Comment by orius123** [comment]
@meirwah @meshipeer @oritstone @Bonczidai @hararzafrir @tudorlesan @SamMarkowitz
I took your images from github, and deployed a demo to [dev site](https://openscoredev.herokuapp.com)
will deploy to production in [countdown](http://datecountdown.com/?&d=4%2f28%2f2015+4%3a00+PM&t=Deploy+New+Images)
> "speak now or forever hold your peace"

**Comment by meirwah** [comment]
:+1: 
Let's merge this!!!
