### ISSUE TITLE
Performance issues on website

### ISSUE THREAD

**Issue by meirwah** [CloudSlang/CloudSlang.github.io#65]
when running a 10 min 50 simultaneous vusers on website, entered website and it looked like this:

![image](https://cloud.githubusercontent.com/assets/6059211/6921655/da93f19a-d7ce-11e4-8092-c83c02f412e0.png)

**Comment by meirwah** [comment]
![image](https://cloud.githubusercontent.com/assets/6059211/6922208/42040b46-d7d2-11e4-98d0-2c7e4df86840.png)

**Comment by orius123** [comment]
we need a more concrete issue
