### ISSUE TITLE
 community link leads to wrong place

### ISSUE THREAD

**Issue by meirwah** [CloudSlang/CloudSlang.github.io#68]
When you press the community link(upper toolbar) you get to the images section...

![image](https://cloud.githubusercontent.com/assets/6059211/6959609/8ac6a2c4-d923-11e4-989f-0a5b79ff23ad.png)

Using Chrome

**Comment by oritstone** [comment]
It is working. The community section is the bottom part of the page, and it is seen when you press it. It's height is smaller than the others...
