### ISSUE TITLE
Documentation around commands should be improved in particular related to: a. “default” options examples b.  Actual examples when TAB

### ISSUE THREAD

**Issue by meshipeer** [CloudSlang/CloudSlang.github.io#74]
Steps: Let’s consider the run command
1. Issue the run command simply by run
   Actual result: One is prompted with “You should specify a default option (otherwise known as option 'f') for this command”.
   Expected result: One should know what to do after this message (run --f, run –f run f, what?!) through a short example maybe?
   Note: for instance if you trigger run –f you end up with the same message as above which is not ok.
2. Now Issue the run command by run –f and press TAB
   Actual result: you are prompted with two options that do not state anything? What file I need to provide?
   Expected result: run command help (simple one and not the complex "help run") and example should be provided

**Comment by SamMarkowitz** [comment]
The explanation makes this look like an issue with the error messages, not the docs.

**Comment by andreivasiletruta** [comment]
This issue was moved to CloudSlang/docs#279
