### ISSUE TITLE
Slang Tutorials page width should be 100% of the screen

### ISSUE THREAD

**Issue by oritstone** [CloudSlang/CloudSlang.github.io#78]

**Comment by orius123** [comment]
@SamMarkowitz this apply now also for the docs
@oritstone

**Comment by oritstone** [comment]
@SamMarkowitz is there a way in red-the-docs to configure the content to take the entire page width?

**Comment by SamMarkowitz** [comment]
Right now, using ReadTheDocs as is, we don't have much control over anything.

**Comment by andreivasiletruta** [comment]
closing this issue. It relates to the ReadTheDocs and not the website and there is nothing on this side that we plan to improve at the moment
