### ISSUE TITLE
Links after scroll

### ISSUE THREAD

**Issue by SamMarkowitz** [CloudSlang/CloudSlang.github.io#81]
If a link is clicked the page scrolls to the target as expected. If the user then scrolls back to the link and clicks it again, the page does not scroll back to the target of the link.

**Comment by oritstone** [comment]
@SamMarkowitz is this still an issue?

**Comment by SamMarkowitz** [comment]
@oritstone  Yes. Still an issue.

**Comment by orius123** [comment]
Moving docs to read the docs
