### ISSUE TITLE
Score word under the old icon + weird url in the middle - in blog post "Health Checking Docker Most Popular Images: MySQL"

### ISSUE THREAD

**Issue by michalhugim** [CloudSlang/CloudSlang.github.io#82]
See this post:
http://blog.cloudslang.io/2015/01/health-checking-docker-most-popular.html

![scoreblog](https://cloud.githubusercontent.com/assets/10436430/7111771/fdb815be-e1cb-11e4-8415-aa8fc4dd1163.png)

**Comment by SamMarkowitz** [comment]
Fixed.

**Comment by michalhugim** [comment]
That was fast☺
