### ISSUE TITLE
Should be "Day-2 Operations"

### ISSUE THREAD

**Issue by avigail-oron** [CloudSlang/CloudSlang.github.io#87]
and not Day 2 Operations

**Comment by SamMarkowitz** [comment]
My findings were that more people write it without the hyphen.

**Comment by avigail-oron** [comment]
Even when used as an adjective?

**Comment by SamMarkowitz** [comment]
Just reporting what I see: https://www.google.com/search?q=%22day-2+operations%22.

In cases like these (new terms, etc.) my opinion is that it's best to go with how people are using it over what might be technically more correct.

**Comment by avigail-oron** [comment]
you are the expert :-)
